// frontend/vue-project/src/components/Card.vue
<script setup>
    import { computed } from 'vue'
    const props = defineProps(['name','description','count'])

    const name = props.name || 'MyCatalog - header'
    const description = props.description || 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente omnis dicta vero ipsam atque quae, suscipit reprehenderit non nisi delectus.'
    const count = props.count || 0
</script>

<template>
    <div class="card">
        <header>{{name}}</header>
        <section class="content">
            {{description}}
        </section>
        <footer>
            <button v-if="count > 0" class="btn-buy">Produto disponível</button>
            <p v-else><small>Produto fora da loja</small></p>
        </footer>
    </div>
</template>

<style>
</style>

// frontend/react-app/src/App/Card.js


export default function Card(props) {

    const title = props.title || 'MyCatalog - header'
    const description = props.description || 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente omnis dicta vero ipsam atque quae, suscipit reprehenderit non nisi delectus.'
    const count = props.count || 0

    return (
        <div className="card">
            <header>{title}</header>
            <section className="content">
                {description}
            </section>
            <footer>
                { count > 0 ? 
                    <button className="btn-buy">Produto disponível</button>
                    :
                    <p><small>Produto fora da loja</small></p>
                }
            </footer>
        </div>
    )
}
