// frontend/vue-project/src/components/Card.vue
<script setup>
    import { computed } from 'vue'
    const props = defineProps(['name','description','count'])

    const name = props.name || 'MyCatalog - header'
    const description = props.description || 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente omnis dicta vero ipsam atque quae, suscipit reprehenderit non nisi delectus.'
    const count = props.count || 0
</script>

<template>
    <div class="card">
        <header>{{name}}</header>
        <section class="content">
            {{description}}
        </section>
        <footer>
            <button v-if="count > 0" class="btn-buy">Produto disponível</button>
            <p v-else><small>Produto fora da loja</small></p>
        </footer>
    </div>
</template>

<style>
</style>

// frontend/angular-app/src/app/card/card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import Product from '../model/product';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html'
})
export class CardComponent implements OnInit {

  @Input() product!: Product;

  constructor() { }

  ngOnInit(): void {
  }

}


    <header>{{product.name || 'MyCatalog - header'}}</header>
    <section class="content">
        {{
            product.description
            ||
            'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente omnis dicta vero ipsam atque quae, suscipit reprehenderit non nisi delectus.'
        }}
    </section>
    <footer>
        <button *ngIf="product.count > 0; else noCount" className="btn-buy">Produto disponível</button>
        <ng-template #noCount>
            <p><small>Produto fora da loja</small></p>
        </ng-template>
    </footer>
