// frontend/react-app/src/App/index.js

import { useState } from 'react'
import Card from './Card.js'

export default function App(props) {

    const [products, setProducts] = useState([
        {
            id: 1,
            name: 'teste',
            description: 'Este é um belo produto',
            count: 5
        }, {}, {}, // just for tests
    ])
    const [layout, setLayout ] = useState(0)
    const className = layout == 0 ? 'grid' : 'flex'

    const toggleLayout = (value) => {
        setLayout(value)
    }

    return (
        <main>
            <header>
                <h3 className="title">MyCatalog</h3>

                <div className="options">
                    <button className={layout == 0 ? 'active' : ''} onClick={() => toggleLayout(0)}>Grid</button>
                    <button className={layout == 1 ? 'active' : ''} onClick={() => toggleLayout(1)}>Flex</button>
                </div>
            </header>
            <section id="content" className={className}>
                {
                    products.map((product) => (
                        <Card {...product} key={product.id} />
                    ))
                }
            </section>
            <footer>
                <p>Feito por Christian Oliveira</p>
            </footer>
        </main>
    )
}

// frontend/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import Product from './model/product'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./grid.css','./flex.css']
})
export class AppComponent {
  layout = 0;
  products: Array<Product> = [
    {
        name: 'teste',
        description: 'Este é um belo produto',
        count: 5
    },
    {
        name: 'teste 2',
        description: 'Este é um belo produto 2 ',
        count: 0
    },
    {
        name: 'teste 3',
        description: 'Este é um belo produto 3',
        count: 5
    },
  ]

  toggleLayout(value: number) {
    this.layout = value
  }
}

<main>
    <header>
        <h3 class="title">MyCatalog</h3>

        <div class="options">
            <button [class]="layout == 0 ? 'active' : ''" (click)="toggleLayout(0)">Grid</button>
            <button [class]="layout == 1 ? 'active' : ''" (click)="toggleLayout(1)">Flex</button>
        </div>
    </header>
    <section id="content" [class]="layout == 0 ? 'grid' : 'flex'">
        <app-card class="card" *ngFor="let product of products" [product]="product" ></app-card>
    </section>
    <footer>
        <p>Feito por Christian Oliveira</p>
    </footer>
</main>
